use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'YJAdMob_Example' do
  pod 'YJAdMob', :path => '../'

  target 'YJAdMob_Tests' do
    inherit! :search_paths

    
  end
end
